### PR TITLE
Fannkuch redux d

### PR DESCRIPTION
**Pull request by cyrusmsk**
Added different implementations in D:
1 : from 1.cr
1-i, 1-im : from 1-im.cpp
2-i : from 2-i.rs
2-im : from 2-im.rs

It is just a ported version of code from different languages. Better and more iDiomatic code could be added later.

### CODE REVIEW

**Comment by hanabi1224** [comment]
Looks like there're merge conflicts

**Comment by cyrusmsk** [comment]
> Looks like there're merge conflicts

It seems the problem with bench_d.yaml
I don’t know why the new part for this problem git assessed as conflict

**Comment by cyrusmsk** [comment]
@hanabi1224 do you know what to do to eliminate this conflict?

**Comment by cyrusmsk** [comment]
@hanabi1224 now the conflict should be resolved.

**Pull request merged**
