### PR TITLE
tlsEmulation off for nim builds

### PR DESCRIPTION
**Pull request by planetis-m**
There is a know performance regression caused by the tlsEmulation switch when threads:on, turn it off.

### CODE REVIEW

**Comment by planetis-m** [comment]
I don't know if it's ok to switch the C complier to clang, it usually produces faster executables.

**Comment by hanabi1224** [comment]
Sure you can use clang-14, gcc or zig cc as backend, either replace current one or make it side by side, plz refer to the setup in [bench_v.yaml](https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/bench_v.yaml)

**Comment by planetis-m** [comment]
Ok, I don't know what's -x:off -y:off and I am pretty sure --opt:speed is implied by -d:release anyway it's good to go.

**Comment by hanabi1224** [comment]
According to `nim --fullhelp`

```
-x, --checks:on|off       turn all runtime checks on|off
-a, --assertions:on|off   turn assertions on|off
```

**Comment by planetis-m** [comment]
It may worth to in the future to add -d:useMalloc too.

**Comment by planetis-m** [comment]
```/bin/sh: 1: clang: not found```

**Comment by hanabi1224** [comment]
Can u plz elaborate on why removing several options?  What's the downside of setting them explicitly?

**Comment by planetis-m** [comment]
Well average user (like me) won't bother turning each check off but there is a -d:danger switch for stuff like benchmarking, which was already used. So it won't make any difference in the results. -d:danger was changed to 'superset' -d:release a while ago, so -d:release can be removed to. The only option that makes a difference are --threads:on --tlsemulation:off, which is slower than assuming single threaded, and --mm:orc

**Comment by hanabi1224** [comment]
Sounds good, thx. After doing some search, I can also confirm that from this [unoffical FAQ](https://github.com/nim-lang/Nim/wiki/Unofficial-FAQ#is-nim-unsafe). 

BTW, I really wish it could appear in the official doc and `nim --fullhelp` output, also it will be very helpful to mark which option is default for the switches

**Pull request merged**
