### PR TITLE
Fasta D version

### PR DESCRIPTION
**Pull request by cyrusmsk**
based on Zig code

### CODE REVIEW

**Comment by hanabi1224** [comment]
Thanks! Please also update bench_d.yaml to include this new file and make sure tests pass locally

**Comment by cyrusmsk** [comment]
@ssvb could be so kind to review the quality of the code. Maybe you could suggest some performance improvements

**Comment by cyrusmsk** [comment]
> Thanks! Please also update bench_d.yaml to include this new file and make sure tests pass locally

Added bench_d and fasta tests passed based on dotnet tool from bench folder

**Comment by hanabi1224** [comment]
thanks

**Pull request merged**
