### PR TITLE
Improve Nim coro-prime-sieve implementation so that it does not timeout

### PR DESCRIPTION
**Pull request by navid-m**
The current implementations timeout for the input value 4000. This one does not.

### CODE REVIEW

**Comment by hanabi1224** [comment]
Thanks for you PR. However, this does not seem to be coroutine based. Please note `coro-` in the problem name means coroutine.

**Comment by navid-m** [comment]
This uses coroutines, and is not as slow as the existing implementations, any input before I change PR?

```nim
import std/[
  os,
  strutils,
  coro
]

var 
  numbers: seq[int]
  primesNeeded: int
  primesFound = 0

const TICK_RATE = 0.0005

proc generateNumbers() =
  ## Generate the numbers from 2
  var i = 2
  let limit = int(high(int16)) * 3
  while i <= limit:
    numbers.add(i)
    inc i
    if i mod 1000 == 0:
      suspend()

proc filterAndPrint() =
  ## Filter numbers and print primes
  var i = 0
  while primesFound < primesNeeded:
    if i >= numbers.len - 1:
      break
    let prime = numbers[i]
    echo prime
    inc primesFound
    var filtered = newSeq[int]()
    for num in numbers:
      if num == prime or num mod prime != 0:
        filtered.add(num)
    numbers = filtered
    inc i
    suspend(TICK_RATE)

when isMainModule:
  primesNeeded = if paramCount() < 1: 100 else: parseInt(paramStr(1))
  discard start(generateNumbers)
  discard start(filterAndPrint)
  run()
```

**Comment by hanabi1224** [comment]
Removing the usage of channel or its equivalent still makes it incomparable to others. Please refer to the [go implementation](https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/algorithm/coro-prime-sieve/1.go)

**Comment by navid-m** [comment]
This uses channels. Good now?

```nim
import std/[
  os,
  strutils,
  coro
]

var
  numbers: seq[bool]
  primesChan: Channel[int]
  primesNeeded: int

primesChan.open()

proc generateNumbers() =
  let limit = int(high(int16)) * 3
  numbers = newSeq[bool](limit + 1)
  for i in 2..limit:
    numbers[i] = true
  suspend()

proc sieveAndSend() =
  let limit = numbers.len - 1
  var found = 0
  for i in 2..limit:
    if numbers[i]:
      primesChan.send(i)
      inc found
      if found >= primesNeeded:
        break
      var j = i * i
      while j <= limit:
        numbers[j] = false
        j += i
      suspend()

proc printPrimes() =
  var received = 0
  while received < primesNeeded:
    echo primesChan.recv()
    received.inc
    suspend()

when isMainModule:
  primesNeeded = if paramCount() < 1: 100 else: parseInt(paramStr(1))
  discard start(generateNumbers)
  discard start(sieveAndSend)
  discard start(printPrimes)
  run()
```

**Comment by navid-m** [comment]
He ran out of random made up bullshit rules, I suppose.

**Pull request closed without merging**
