### PR TITLE
zig pidigits - audit memory usage

### PR DESCRIPTION
**Pull request by travisstaloch**
- generally clean up this solution which was allocating a lot of
  extra temporary bigints.
- don't bother deinit()ing anything
- use a 320kb fixed buffer allocator for temporary values
- k doesn't need to be a bigint

### CODE REVIEW

**Comment by hanabi1224** [comment]
Thanks, this is a great improvement! However, the `320kb fixed buffer allocator` makes it quite different from other solutions, could u just allocate the `tmp` and `tmp2` once outside the loop without deinitializing, just like `v` and `w` in the original code.  Regarding `k`, I think it's better to keep it bigint to make it comparable to other solutions. To be fair, there're optimizations to make it stack allocated in some libraries, like in [`2.rs`](https://github.com/hanabi1224/Programming-Language-Benchmarks/blob/main/bench/algorithm/pidigits/2.rs), the [`ibig`](https://docs.rs/ibig/latest/src/ibig/ubig.rs.html#14) crate allocate small values on stack and big ones on heap, but I would try to make the solution code comparable and expect the optimization to come from the bigint lib itself, cuz this problem is essentially comparing the bigint lib

**Comment by travisstaloch** [comment]
Thanks for the guildance.  I agree with your assessments.  Best to have similar solutions which show language differences.  Its can be tough to balance making a similar solution to the others and wanting to create a fast one.  While zig is generally very performant, its general purpose allocator hasn't yet been well optimized.  Its mainly focused on helping discover memory errors.  So I try to work around its performance at times.  

I assumed that the gpa was preferred from looking at the other zig solutions.  I think most of those which use an allocator would see a significant improvement just from switching out the gpa for `std.heap.c_allocator`.  I've verified in this solution for example that my local times for 8000 digits go from around 2.1s w/ gpa to around 1.4s with malloc/free.  Would you like to receive solutions which use the c_allocator?

**Comment by hanabi1224** [comment]
> Would you like to receive solutions which use the c_allocator

I think so if it's a drop in replacement. 

P.S. I'm also curious to learn about their differences and may or may not change my mind later cuz I'm just a zig beginner atm

**Comment by travisstaloch** [comment]
Yes, using the heap.c_allocator is a one line (actually -2/+1 line) drop in replacement for the gpa. just `const global_allocator = std.heap.c_allocator;`

Aside from the link you provided, these may be of interest:
A quick summary of zig allocators:  https://ziglearn.org/chapter-2/
The GPA source (has a pretty good summary at the top):  https://github.com/ziglang/zig/blob/master/lib/std/heap/general_purpose_allocator.zig

**Comment by hanabi1224** [comment]
Thanks!

**Comment by travisstaloch** [comment]
Looking forward to seeing the differences.  Do you know if the numbers shown [here](https://programming-language-benchmarks.vercel.app/rust-vs-zig) for example are already showing these changes? I only see a date. Might be nice to show a time as well unless i just missed it somewhere.

**Comment by travisstaloch** [comment]
oic, there is a link to the full log. think those are from 20 hours ago so maybe in another 4 hours.

**Comment by hanabi1224** [comment]
Check out the [CI page](https://github.com/hanabi1224/Programming-Language-Benchmarks/actions/workflows/bench.yml), it should be finished in ~2 hours and the result will be automatically published

**Pull request merged**
