### PR TITLE
Use Task and Queue of asyncio.

### PR DESCRIPTION
**Pull request by lohaswinner**
Remove setrecursionlimit

### CODE REVIEW

**Comment by hanabi1224** [comment]
Thanks, could you make it `2.py` instead?

**Comment by lohaswinner** [comment]
> Thanks, could you make it `2.py` instead?

I have been considering 1.py is wrong. It's just recursion with coroutine. So i fixed it.
Is it the maintaining policy that making the new file with number up?

**Comment by lohaswinner** [comment]
@hanabi1224 Do you have any idea?
If you don't want to merge this change, just close this PR.
If any comment were not to be written, I would close it.

**Comment by lohaswinner** [comment]
Thanks for watching my work. Now I am closing this PR.

Recently I know Java virtual thread, and I have learned about concurrent programming with some programming languages. I found your benchmark web site. Specially your C# and Java source code of coro-prime-sieve is instructive to me. Thank you.

**Pull request closed without merging**
