### PR TITLE
Bump allocate binarytree

### PR DESCRIPTION
**Pull request by LHolten**
Hi!

This looks like a fun project!
I felt like adding bump allocation to the rust implemention of binarytree.
This makes allocation and deallocation very cheap.
So it runs around 4x faster.

Do with it what you want.

Have a nice day,
Lucas

### CODE REVIEW

**Comment by hanabi1224** [comment]
Thanks, but sorry arena-ish allocations are [not accepted](https://benchmarksgame-team.pages.debian.net/benchmarksgame/description/binarytrees.html#binarytrees) for this problem.

**Comment by LHolten** [comment]
I'm sorry @hanabi1224.
The reason I thought it might be accepted is because it was accepted in the benchmark game [issue](https://salsa.debian.org/benchmarksgame-team/benchmarksgame/-/issues/397) and [submission](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/binarytrees-rust-5.html).
But I understand you have a more principled approach. :+1:
Could I suggest removing languages that don't use garbage collection from this test completely?
Or maybe add an explanation to the problem page that the test measures the speed of the default allocator/ garbage collection.

**Comment by LHolten** [comment]
Would a submission that uses a different general purpose global allocator like mimalloc or jemalloc be accepted?

**Comment by hanabi1224** [comment]
> Would a submission that uses a general purpose global allocator like mimalloc or jemalloc be accepted?

I'd like to if the allocator is language native. Otherwise, it will add maintenance costs without showing unique value cuz it can also be employed by other langs

**Pull request closed without merging**
