### PR TITLE
binarytrees benchmark for swift

### PR DESCRIPTION
**Pull request by acefsm**

### CODE REVIEW

**Comment by hanabi1224** [comment]
Can you make it single-threaded? No multi-threaded solutions are listed for this problem

**Comment by acefsm** [comment]
> Can you make it single-threaded? No multi-threaded solutions are listed for this problem

done

**Comment by hanabi1224** [comment]
Tests did not pass: https://github.com/hanabi1224/Programming-Language-Benchmarks/actions/runs/4267678984/jobs/7429534652#step:39:136

**Comment by acefsm** [comment]
> Tests did not pass: https://github.com/hanabi1224/Programming-Language-Benchmarks/actions/runs/4267678984/jobs/7429534652#step:39:136

fixed

**Comment by hanabi1224** [comment]
Thanks

**Pull request merged**
