### PR TITLE
Add Acton programs for binarytrees, merkletrees and nsieve

### PR DESCRIPTION
**Pull request by plajjan**

### CODE REVIEW

**Comment by hanabi1224** [comment]
Thanks! But I believe `bench_acton.yaml` needs to be updated as well.

**Comment by plajjan** [comment]
@hanabi1224 doh, fixed now. Since this change would conflict with other branches, I have folded multiple PRs into this one, including #391, #394 and #393.

**Comment by plajjan** [comment]
Now also rebased on latest main, I think this is ready @hanabi1224 :)

**Comment by plajjan** [comment]
@hanabi1224 I've rebased this branch and I believe it is ready for merging!

**Comment by plajjan** [comment]
@hanabi1224 I rebased this branch, ready for merge!

**Comment by hanabi1224** [comment]
Thanks!

**Pull request merged**
